version: '3.8'
services:
  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./src:/usr/share/nginx/html
    depends_on:
      - backend
      - db
  backend:
    image: iting945/php_apache_pdomysql
    ports:
      - "8080:80"
    volumes:
      - ./api:/var/www/html/api/
    depends_on:
      - db
  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: admin 
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
  